In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [2]:
df = pd.read_csv('Resources/cleaned_data.csv')
df = df.drop(['season','player'],axis=1)
df.head()

,position,age,experience,team,games,games_started,minutes_played,fieldgoals,fieldgoals_attemped,three_points_made,...,offensive_rebounds,defensive_rebounds,total_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,playoffs
0,PF,25.0,7,ORL,25.0,25.0,736.0,128.0,293.0,42.0,...,39.0,127.0,166.0,105.0,16.0,20.0,67.0,49.0,364.0,0.0
1,PF,25.0,7,DEN,25.0,25.0,648.0,103.0,206.0,17.0,...,38.0,80.0,118.0,56.0,17.0,14.0,30.0,40.0,254.0,0.0
2,PG,24.0,3,IND,66.0,8.0,1176.0,170.0,436.0,67.0,...,15.0,74.0,89.0,123.0,46.0,13.0,66.0,94.0,475.0,0.0
3,SF,21.0,1,BOS,46.0,1.0,669.0,78.0,178.0,40.0,...,28.0,99.0,127.0,23.0,15.0,9.0,23.0,87.0,218.0,0.0
4,SF,27.0,4,PHO,24.0,0.0,355.0,57.0,116.0,18.0,...,7.0,55.0,62.0,19.0,10.0,9.0,19.0,34.0,160.0,0.0

In [3]:
le = LabelEncoder()

# Create our features
#X = df.apply(LabelEncoder().fit_transform)
X = pd.get_dummies(df)
#X.drop('loan_status', axis=1)

# Create our target
y = le.fit_transform(df['playoffs'])
#y= df['loan_status']

print(y)
#y.describe()

[0 0 0 ... 1 1 1]

In [4]:
X.describe()
test = pd.get_dummies(df)
#test.describe()

X.describe()

,age,experience,games,games_started,minutes_played,fieldgoals,fieldgoals_attemped,three_points_made,three_point_attempts,two_point_made,...,team_ORL,team_PHI,team_PHO,team_POR,team_SAC,team_SEA,team_TOR,team_UTA,team_VAN,team_WSB
count,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,...,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000,15074.000000
mean,26.688802,5.381651,48.657423,23.757131,1148.298992,183.993499,397.938371,25.787780,73.247778,158.205718,...,0.036619,0.048560,0.045111,0.042391,0.040600,0.027265,0.031976,0.040998,0.006501,0.016983
std,4.071894,3.905992,26.916440,28.812067,923.949816,181.469290,378.967820,41.942964,111.334306,165.980396,...,0.187832,0.214954,0.207554,0.201486,0.197368,0.162861,0.175941,0.198292,0.080371,0.129211
min,18.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,2.000000,24.000000,0.000000,293.250000,34.000000,82.000000,0.000000,2.000000,27.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,4.000000,53.000000,8.000000,967.000000,127.500000,285.000000,4.000000,16.000000,102.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,29.000000,8.000000,75.000000,46.000000,1881.750000,285.750000,619.000000,35.000000,104.000000,239.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,44.000000,22.000000,82.000000,82.000000,3485.000000,1098.000000,2279.000000,378.000000,1028.000000,1086.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
# Check the balance of our target values
#['loan_status'].value_counts()
Counter(y)

Counter({0: 6771, 1: 8303})

# from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

In [6]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

NameError: name 'X_train' is not defined

In [ ]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

In [ ]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

# Smote?

In [ ]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

# Display the confusion matrix
confusion_matrix(y_test, y_pred)
balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

# Easy Ensemble

In [ ]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

# Create a easy ensemble classifier
ada_model = EasyEnsembleClassifier(n_estimators=128, random_state=1) 

# Fitting the model
ada_model = ada_model.fit(X_train_scaled, y_train)
predictions = ada_model.predict(X_test_scaled)

In [ ]:
# Calculated the balanced accuracy score
y_pred2 = ada_model.predict(X_test)
confusion_matrix(y_test, y_pred)

print(cm)